openapi: 3.1.0
info:
  version: 1.0.0
  title: My Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    This is a documentation of Contacts App.

tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.

servers:
  - url: https://nodejs-hw-mongodb-k6jr.onrender.com/api
    description: Production server
  - url: http://localhost:3000/api
    description: Local development server

paths:
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/getAll.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'

  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contacts/{contactId}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{contactId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{contactId}/delete.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
